### ISSUE TITLE
Debug VSCode

### ISSUE THREAD

**Issue by octavonu** [SAP-samples/cloud-cap-samples#10]
Hello,

You have written: 
_For example, in VS Code switch to Debug view and launch one of the prepared cds run launch configurations._

I have started the debugger then I can see 
Debugger listening on ws://127.0.0.1:47299
Debugger attached.
Waiting for the debugger to disconnect...

Unfortunately, I am not able to connect with chrome://inspect.

Can you please tell me what am I doing wrong?
Thank you

![image](https://user-images.githubusercontent.com/50553626/69090954-9b24ec00-0a49-11ea-9eb9-5e62fd2a7876.png)

My launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "cds run",
            "request": "launch",
            "type": "node", "runtimeExecutable": "npx","runtimeArgs": ["-n"],  
            "program": "${workspaceFolder}\\srv\\cat-service.js",         
            "args": ["--", "cds","run","--in-memory?" ], // the leading "--" arg ensures it works with as well as without debugging    
            "console": "integratedTerminal",
            "skipFiles": [ "<node_internals>/**" ]
        }
    ]
}

**Comment by chgeo** [comment]
This has been reported in SAP-samples/cloud-cap-nodejs-codejam#15.  Please see there for a better version of launch.json.
