### ISSUE TITLE
other db option.

### ISSUE THREAD

**Issue by babuilyas** [SAP-samples/cloud-cap-samples#100]
I embrace the new standard but wonders what if I want to use other db like oracle, mssql or other than sqlite/hana. I hope and know this is very common question for many.

**Comment by babuilyas** [comment]
century! :)

**Comment by gregorwolf** [comment]
Please check out [CAP integration with PostgreSQL database](https://answers.sap.com/questions/13078147/cap-integration-with-postgresql-database.html) and follow [Create PostgreSQL adapter #88](https://github.com/sapmentors/cap-community/issues/88)
