### ISSUE TITLE
/cds/cxn#operators - inconsistent description of "(" ")"

### ISSUE THREAD

**Issue by hrennau** [SAP-samples/cloud-cap-samples#105]
https://cap.cloud.sap/docs/cds/cxn#operators

The text says:  
"Parts enclosed in parentheses are represented as nested {xpr:...}"
However, the example given does not fit:
> 

cds.parse.expr(`x<9 and (y=1 or z=2)`)  ==//> returns:
{xpr:[
  {ref:['x']}, '<', {val:9}, 'and', '(',
    {ref:['y']}, '=', {val:1}, 'or', {ref:['z']}, '=', {val:2}
  ')'
]}

Note the "(" and ")" - there should be {xpr:[...]} instead.

**Comment by chgeo** [comment]
Thanks for bringing this up.  We will fix this in the next release of the documentation.
