### ISSUE TITLE
Mashup in DKOM branch is not wokring

### ISSUE THREAD

**Issue by simfer** [SAP-samples/cloud-cap-samples#106]
Hi,
I cloned this repository and switched to the DKOM branch.
I opened the project with VSCode and selected the req.http file.
When I try to run the GET Orders expanding on shippingAddress I get the "Unauthorized" error

![01](https://user-images.githubusercontent.com/6877529/85846465-261b5100-b7a6-11ea-8d9a-1baf8aa00c90.png)

then, if I try by using only the "ALICE" user without password, I get "Not Found"

![02](https://user-images.githubusercontent.com/6877529/85846489-2ca9c880-b7a6-11ea-8501-d6a107cc77f0.png)

Where is the problem?

Simmaco

**Comment by chgeo** [comment]
@David-Kunz can you check this?  Is the code in the branch still up to date?

**Comment by David-Kunz** [comment]
Hi @simfer ,

This branch is not up-to-date and not meant for public consumption.

Best regards,
David

**Comment by chgeo** [comment]
For service consumption, please refer to this branch:
 
https://github.com/SAP-samples/cloud-cap-samples/tree/openSAP-week4-unit3-final
