### ISSUE TITLE
Fuzzy search in custom handler

### ISSUE THREAD

**Issue by hmpbmp** [SAP-samples/cloud-cap-samples#107]
Hello,

Please kindly provide any information on how I can use HANA fuzzy search in CDS.
I've checked (cap-fuzzy-search)[https://github.com/JoseMunozHerrera/cap-fuzzy-search/] and it is using the $search option in OData but it seems that starting from March 2020 it is converted to LIKE statement and doesn't handle function other than CONTAINS and CONCAT.
Is there a way to use FUZZY with CQL or CQN.

If no, what are recommendations on how to use it with CDS in HANA/XSA.

Thank you

**Comment by chgeo** [comment]
This issue channel will be closed soon.  If the error persists, please report it in our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).
