### ISSUE TITLE
/cds/csn - no mention of the "includes" keyword

### ISSUE THREAD

**Issue by hrennau** [SAP-samples/cloud-cap-samples#108]
https://cap.cloud.sap/docs/cds/csn -

this documentation does not mention the "includes" keyword, which may occur in CSN documents obtained from the cds command-line tool. Note also that the cdl documentation contains a CSN snippet containing "includes" (example: "contexts.json").

**Comment by bugwelle** [comment]
Thanks for bringing this up. We will update the documentation accordingly.

To put it short: `includes` is used for extending entities. For example, take this CDL file:

```swift
entity A {
  a : String;
}
// See https://cap.cloud.sap/docs/cds/cdl#shortcut-syntax-
entity E : A {
  key id : Integer;
};
```
This will produce following CSN:

```json
{
  "definitions": {
    "A": {
      "kind": "entity",
      "elements": {
        "a": {
          "type": "cds.String"
        }
      }
    },
    "E": {
      "kind": "entity",
      "includes": [
        "A"
      ],
      "elements": {
        "a": {
          "type": "cds.String"
        },
        "id": {
          "key": true,
          "type": "cds.Integer"
        }
      }
    }
  }
}
```

`definitions.E.includes` is an array of e.g. entity names that shall be used to extend the entity. In this case, entity `E` inherits all elements from `A`. If you write the CSN by hand, it is not necessary to add `A`'s elements to `E`. The `includes` property would be enough to tell CDS that all elements shall be inherited.


Regards,
Andre

**Comment by hrennau** [comment]
Thank you, Andre, for this neat explanation! Which seems to confirm what I thought: the values of "includes" MUST be the names of entities in scope.

**Comment by chgeo** [comment]
Documentation has been updated: https://cap.cloud.sap/docs/cds/csn#structured-types
