### ISSUE TITLE
Creation of new Order using the fiori app shows a popup box for ID

### ISSUE THREAD

**Issue by kachrafaltu** [SAP-samples/cloud-cap-samples#112]
This issue was also reported by another user in the community and I have upvoted it since I have the same issue.
https://answers.sap.com/questions/13091274/sample-fiori-app-creating-a-new-order-shows-a-popu.html
I have the latest version of the CDS registry and have changed the registry to point to the npmjs registry as required by June release. I am suspecting this issue is a result of the bugfix for GUIDs in general. I found this issue with another application I am developing. I am also attaching my screenshot and the community page also has a similar screenshot.

![image](https://user-images.githubusercontent.com/62317637/87228327-7e3d8000-c36e-11ea-955e-ec1ec9bab161.png)

It appears June release had a bug fix for UUIDs and this is the detail from the capire web page.
"UUIDs in OData requests are now normalized by converting them to lowercase."

**Comment by sbarzaghialteaup** [comment]
I hope this can help:

The popup seems a new behaviour in sapui5 from 1.79.0, sapui5 fe now during a document creation shows a popup with all the not computed and visible key fields:

(https://sapui5.hana.ondemand.com/1.79.0/resources/sap/fe/core/TransactionHelper-dbg.js?eval line 259).

```
if (aNonComputedVisibleKeyFields.length > 0) {
        ...
	oCreationPromise = this._launchDialogWithKeyFields(
		oMainListBinding,
		oTransientListBinding,
		oNewDocumentContext,
		aNonComputedVisibleKeyFields,
		oModel,
		mParameters
	);
```

CDS aspect "cuid" define the field key "ID" without the annotation "@Core.Computed".

I tried to add "@Core.Computed" in @sap\cds\common.cds and the popup disappered.

**Comment by chgeo** [comment]
We want to close this issues channel soon, in favor of our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).  Can you raise the question there, or use the existing question linked above?

Thanks,
Christian
