### ISSUE TITLE
post requests to CAPM service deployed on CF

### ISSUE THREAD

**Issue by HarshalRN** [SAP-samples/cloud-cap-samples#134]
I am trying to perform post request to CAPM service via postman but getting error while posting .

I tried to post using  SAP Business studio it is working fine over there but if i try to do post from postman it is not working.

Postman post request:
![image](https://user-images.githubusercontent.com/71324807/93204541-e431f380-f773-11ea-80c3-997fe1462222.png)

BAS post request:
![image](https://user-images.githubusercontent.com/71324807/93204702-265b3500-f774-11ea-9cd8-431c1a43c305.png)

**Comment by chgeo** [comment]
We are about to close this channel.  Please use our [community](https://cap.cloud.sap/docs/ask-question-vscode).
Thanks.
