### ISSUE TITLE
Annotation with absolute path

### ISSUE THREAD

**Issue by ghiblin** [SAP-samples/cloud-cap-samples#165]
Fiori Elements does not support native user authorization, so I created an OData Singleton with odata singleton annotation.
```xml
<Singleton Name="Auth" Type="AdminService.Auth"/>
```
I'd like to use Capabilities annotiations to hide and show CRUD buttons on List Report/Object pages, as I can config the annotation to use an absolute value  
```xml
<Annotation Term="Capabilities.DeleteRestrictions">
    <Record Type="Capabilities.DeleteRestrictionsType">
        <PropertyValue Property="Deletable" Bool="false"/>
    </Record>
</Annotation>
```
or I can use a path 
```xml
<Annotation Term="Capabilities.DeleteRestrictions">
    <Record Type="Capabilities.DeleteRestrictionsType">
        <PropertyValue Property="Deletable" Path="isDelatable"/>
    </Record>
</Annotation>
```

I'd like to combine the two solution: 
```xml
<Annotation Term="Capabilities.DeleteRestrictions">
    <Record Type="Capabilities.DeleteRestrictionsType">
        <PropertyValue Property="Deletable" Path="/Auth/canDelete"/>
    </Record>
</Annotation>
```

Is this possible with cds?

Thank you and Best Regards

**Comment by chgeo** [comment]
Hey.. we have moved the support channel to the [SAP Community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).  Please file your question there.
