### ISSUE TITLE
[ERROR] ENTITY_ALREADY_EXISTS

### ISSUE THREAD

**Issue by ivanlynch** [SAP-samples/cloud-cap-samples#203]
Hi guys,

I've created a sample project and i can't find any place to ask about it. How can i solve: [ERROR] ENTITY_ALREADY_EXISTS the problem comes up when i modify data from the model.

Regards,

**Comment by chgeo** [comment]
Hi,

just take a look at our [support channels](https://cap.cloud.sap/docs/resources/).  The [SAP Community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) seems to be the right place for such questions.
There, please be more specific on your issue.  What have you done, how can one reproduce it?  If there are error logs, add the whole log, not just one line.

Thanks,
Christian
