### ISSUE TITLE
Fiori App not deployed

### ISSUE THREAD

**Issue by dusk-p** [SAP-samples/cloud-cap-samples#221]
Hello,
I tried to deploy the full application (branch openSAP-week4-unit4) from Business Application Studio to my cloud foundry account but the app is missing. I think the reason is the missing configuration in the mta.yaml file. I was not able to find any example for the app deployment within the openSAP course examples for CAP. Could you enhance the mta.yaml file to enable also the deployment for the frontend?

Thank you in advance for your support

Best Regards
Pierre

**Comment by chgeo** [comment]
Thanks for reaching out.  We are working on more CAP examples which would also include CF deployment.
In the meantime, you can find us on the [SAP Community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce), which is the preferred support channel as it involves more experts.
This is why I am closing this ticket here.
