### ISSUE TITLE
"npm install" command is giving error in SAP Business Application Studio

### ISSUE THREAD

**Issue by RJ1211** [SAP-samples/cloud-cap-samples#224]
Hi Team,

I am trying to learn the CAP course from "https://open.sap.com/courses/cp7/items/5QKEq8Yz5ZcCticDU8KGAz",
and as per Week 1 Unit 4, it asked to follow the steps mentioned in GIT repository "https://github.com/SAP-samples/cloud-cap-samples/tree/openSAP-week1-unit4-final".

But when i run the command "npm install", it gives me error. I have attached the log of the run as well.
[Log for NPM install error.txt](https://github.com/SAP-samples/cloud-cap-samples/files/6354884/Log.for.NPM.install.error.txt)

![Error for npm install](https://user-images.githubusercontent.com/80312875/115643368-a3dabb00-a2ea-11eb-8e6e-5e22791d0f4b.png)

Please let me know how to fix this, as i am new to this CAP and Node JS.

Regards,
Ravi J.

**Comment by gregorwolf** [comment]
Have you tried running your app afterwards? I also see this issue quite often in BAS but it didn't affect the functionality.

**Comment by chgeo** [comment]
Hey, thanks for reaching out.  We want to close this issue channel.  Please use the [SAP community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) instead.  There is just more people listening there.
