### ISSUE TITLE
bookstore cds build fails

### ISSUE THREAD

**Issue by ssimsekler** [SAP-samples/cloud-cap-samples#23]
Hi

When I run the bookstore app, the cds build fails with the following errors:

cds compile failed due to these errors...

 at srv\services.cds:9:49-55: Info: This select item replaces "author" from table alias "Products" (in view:"sap.capire.bookstore.CatalogService.Books"/query:1)
 at srv\services.cds:33:12-31: Error: Cannot find package module '@sap/capire-media'

------
Environment:
Windows 10
node v11.15.0
npm 6.7.0
+-- @sap/cds-dk@1.4.3

Kind Regards

Serdar

**Comment by chgeo** [comment]
@CHERIANS can you take a look here, wrt to the `capire-media` dependency?

**Comment by LakshmiCR** [comment]
Fixed.
