### ISSUE TITLE
Replaceable by a Managed Composition?

### ISSUE THREAD

**Issue by tsteckenborn** [SAP-samples/cloud-cap-samples#240]
Is this still a best practice or should it be replaced by a [managed composition](https://cap.cloud.sap/docs/cds/cdl#for-many-to-many-relationships)?

https://github.com/SAP-samples/cloud-cap-samples/blob/0dc1dc198d4126a8888c2b64f877950dfeca6d24/orders/db/schema.cds#L6

**Comment by danjoa** [comment]
You are right. Actually that version was before we shipped managed compositions. 
@stewsk we should address this when we do the Dreiklang things

**Comment by tsteckenborn** [comment]
While adapting I would appreciate it if someone could take a look at whether he also has the same problem with the delivered ESLint configuration (https://answers.sap.com/questions/13399704/capcds-dkeslint-cds-compilation-failed-managed-com.html).

**Comment by tsteckenborn** [comment]
@danjoa Is there anything that prevents this change? If not, I can submit a PR and replace the few occurrences myself.

**Comment by danjoa** [comment]
I tried that recently and ran into two glitches which prevent us from really doing so → opened #273 now to follow up
