### ISSUE TITLE
CDS service level unit test with restrict

### ISSUE THREAD

**Issue by xtreemrage** [SAP-samples/cloud-cap-samples#241]
I have an issue with unit testing on cds service level testing and the `@restrict` annotation. If I turn this on, my unit test wont work (on a cds level testing, does work with odata level testing).

I have tried to add [dummy authentication](https://cap.cloud.sap/docs/node.js/authentication#dummy) for my test environment in the package.json file:

```json
    "cds": {
        "requires": {
            ...
            "[test]": {
                "auth": {
                    "strategy": "dummy"
                }
            }
        },
       ...
    }
```

According to the docs, this should disable `@requires` and `@restrict`, I hoped this also worked for testing:
> This strategy creates a user that passes all authorization checks. It’s meant for temporarily disabling the @requires and @restrict annotations at development time.

Although `@requires` is no problem, but the `@restrict` is. I have created a sample app in here: https://github.com/xtreemrage/cap-unit-test-restrict. To try it out:
- `git clone`
- `npm i`
- `npm test`

The test will fail because `@restrict` is on. In the file `srv/cat-service.cds` you can turn off the `@restrict` and then it will work!

How can I make sure my CDS service level testing will run with `@restrict` on?

**Comment by chgeo** [comment]
Thanks for reaching out.  Please use the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) to post these questions.
