### ISSUE TITLE
Update the code to match the latest SAP HANA tools

### ISSUE THREAD

**Issue by mcelotti** [SAP-samples/cloud-cap-samples#246]
Hello,
I used this project to get started with the CAP framework as suggested here https://cap.cloud.sap/docs/resources/.
Then I used "cds add mta" to create a mta.yaml file to deploy to the cloud, but at this point I had multiple issues and I managed to fix some of them by taking a look at this post https://blogs.sap.com/2021/01/14/sap-business-application-studio-using-sap-hana-tools-with-sap-cloud-application-programming-model-projects/ 
I wonder if it makes sense to update this project to match the latest SAP HANA tools.

Thanks,
Marco

**Comment by chgeo** [comment]
Thanks for the info.  We know CDS projects need to work better w/ HANA tools (and vice versa).  We are working w/ HANA tools colleagues on this.  Stay tuned for updates in our [releases notes](https://cap.cloud.sap/docs/releases/).
