### ISSUE TITLE
How can I run nodejs service locally and connect to Hana in cloud?

### ISSUE THREAD

**Issue by superwangnan** [SAP-samples/cloud-cap-samples#26]
Hi team,
For java project, we can use "mvn spring-boot:run -Dspring.profiles.active=cloud" to run local service based on remote Hana. But for a nodejs project how can we do the similar thing?
Thanks.

**Comment by chgeo** [comment]
You can use the [profiles](https://cap.cloud.sap/docs/advanced/config#profiles) feature for package.json.  For example:
```json
"requires": {
      "db":  { 
         "model": ["db", "srv"],
         "kind": "sqlite",
         "[hana]": { "kind": "hana" } 
     }
   }
```
You can activate the profile by setting the environment variable `CDS_ENV` to `hana`.

**Comment by superwangnan** [comment]
Thanks got it. : )
