### ISSUE TITLE
BUILD ERROR : npm ERR! @sap/capire-samples@ install: `(npm -s run lerna) && lerna bootstrap --hoist`npm ERR! Exit status 1

### ISSUE THREAD

**Issue by Puneet-devworks** [SAP-samples/cloud-cap-samples#32]
![image](https://user-images.githubusercontent.com/53872672/75428491-4b21c380-596e-11ea-8e30-b56080710f88.png)

Please refer to this snapshot .
This error was faced after trying to build cloud-sap-samples after cloning git repo to web-ide :-

npm install> @sap/capire-samples@ install /sapmnt/C9J/xs/app_working/gcl0139/executionroot/cb1ec35f-570d-4b8e-ba16-680d1e4910c0/app/META-INF/.sap_java_buildpack/tomcat/temp/builder/sap.cds.mta/builds/build-1370146842113914157/cap-samples> (npm -s run lerna) && lerna bootstrap --hoistmodule.js:550    throw err;    ^Error: Cannot find module 'libnpx'

**Comment by Puneet-devworks** [comment]
I also tried to build and run on local machine using vs code which dumped with same error, please find the snap attached - 

![image](https://user-images.githubusercontent.com/53872672/75429381-b4560680-596f-11ea-96ba-b58cc97fa69c.png)

**Comment by chgeo** [comment]
It might be that the install script does work on Windows cmd shell.  Please try it with bash on your Windows machine.

**Comment by Puneet-devworks** [comment]
Hi @chgeo 
This doesnt seem to solve the problem as it seems I need to install node and sqlite separately in order to use bash command line (wsl) with win 10.
Please find the snapshot attached.
![image](https://user-images.githubusercontent.com/53872672/75453112-6a821600-5999-11ea-899c-56e3137f17a2.png)

**Comment by David-Kunz** [comment]
Can you just execute `npx lerna bootstrap --hoist` instead?

**Comment by Puneet-devworks** [comment]
Executed "npx lerna bootstrap --hoist"
Snapshot - 
![image](https://user-images.githubusercontent.com/53872672/75522188-5db00180-5a2f-11ea-9fb7-c5ea14bf8e78.png)

This doesnt solve the problem too because I am receiving same error - "The system cannot find path specified" , when i am trying to build the project , using command - "npm i"

**Comment by Puneet-devworks** [comment]
![image](https://user-images.githubusercontent.com/53872672/75522269-9a7bf880-5a2f-11ea-888c-89d6c49c7984.png)

**Comment by David-Kunz** [comment]
Hi,

`npx lerna bootstrap --hoist` _replaces_ `npm i` in this case, so you don't need to execute `npm i` at all.
The lerna command seems to be successful, i.e. your packages are installed.
To be sure that everything is installed correctly you can also clean up before you bootstrap the files:

```
npx lerna clean -y
npx lerna bootstrap --hoist
```

Best regards,
David

**Comment by chgeo** [comment]
We have removed lerna in the current master, so this should be obsolete.  Just check out the readme for the simplified setup.
