### ISSUE TITLE
'Getting Started in a Nutshell' documentation not working

### ISSUE THREAD

**Issue by wurst0815** [SAP-samples/cloud-cap-samples#36]
Hi guys,
when trying to follow the tutorial https://cap.cloud.sap/docs/get-started/in-a-nutshell I get an error after the step 'Defining Domain Models' when doing it all manually saying 'No service models found':
![image](https://user-images.githubusercontent.com/13557494/77047865-c69eef80-69c5-11ea-978a-09a0eb81152e.png)
So I guess there might be one step missing in the docs?

**Comment by David-Kunz** [comment]
Hi,
This is the correct behaviour (apart from that weird [object Object] string) if you did not yet define any service entities.
This will happen in step `Defining Services`.

Best regards,
David

**Comment by wurst0815** [comment]
Ah... ok I see. Would suggest to mention that in the docs that this is the expected behaviour :-)

**Comment by David-Kunz** [comment]
Hi,
Thanks for the suggestion! We will ship this info in the next release of Capire.
Best regards,
David

**Comment by chgeo** [comment]
> Would suggest to mention that in the docs that this is the expected behaviour :-)

The hint is actually in the [docs](https://cap.cloud.sap/docs/get-started/in-a-nutshell#defining-services), just slightly different...
```
After the recent changes, cds watch also printed this message:

Error: [cds] -
  No service models found in current working directory.
```

**Comment by wurst0815** [comment]
Yeah, but people (like me) might don't continue reading after they receive an error.

Especially when there is other content between the error causing code and the solution for the expected error, in this case the optional model compiling part.

**Comment by David-Kunz** [comment]
Hi,

In the upcoming version of `@sap/cds` there will be no `error` anymore, but rather the following:
```
$ cds watch
 
[cds] - running nodemon... 
--exec cds serve --with-mocks --in-memory? 
--ext cds,csn,csv,ts,mjs,cjs,js,json,properties,edmx,xml 

    No models found at db/,srv/,app/,schema,services,.
    Waiting for some to arrive...
```
So this would be less confusing, what do you think?

**Comment by wurst0815** [comment]
Yes, perfect. 
Thank you.
