### ISSUE TITLE
'Getting Started in a Nutshell' documentation -> minor thing

### ISSUE THREAD

**Issue by wurst0815** [SAP-samples/cloud-cap-samples#37]
The documentation mentiones the commands
`sqlite3 sqlite.db .dump`
`sqlite3 sqlite.db .tables`

which should be 
`sqlite3 my.db .dump`
`sqlite3 my.db .tables`

because that is the given name in
`cds deploy --to sqlite:my.db`

**Comment by David-Kunz** [comment]
Thanks! I created a PR to fix that!

**Comment by chgeo** [comment]
This is fixed in the [documentation](https://cap.cloud.sap/docs/get-started/in-a-nutshell#deploying-persistent-databases).  Thanks for reporting.
