### ISSUE TITLE
cannot install node modules

### ISSUE THREAD

**Issue by mjza** [SAP-samples/cloud-cap-samples#39]
I tried the following command in the sample folder to install node modules but I got the following error:

`c:\samples>npm i`

> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@capire%2fcommon - Not found
> npm ERR! 404
> npm ERR! 404  '@capire/common@^3.31.1' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of '@capire/bookshop'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-03-23T09_45_31_320Z-debug.log

**Comment by David-Kunz** [comment]
Hi Mahdi,
Did you set the correct `npm` repository?
```bash
npm config set @sap:registry https://npm.sap.com
```

Best regards,
David

**Comment by mjza** [comment]
I ran the following command from [here](https://cap.cloud.sap/docs/get-started/):

`npm set @sap:registry=https://npm.sap.com`

**Comment by mjza** [comment]
@David-Kunz I tried your command also. But still the error is there.

**Comment by mjza** [comment]
@David-Kunz if I remove the following line from `bookshop/package.json` then the installation will be done. It just mentioned in the `bookshop` sample:

`"@capire/common": "^3.31.1",`

**Comment by David-Kunz** [comment]
Hi, 
I can reproduce this error, I'll have a look!
Best regards,
David

**Comment by ShivaCharanKoti1991** [comment]
Hi Mahdi, 
command: npm install 
will bring node modules in your packages. 

Shiva.

**Comment by danjoa** [comment]
And ensure to use npm v8 or higher
