### ISSUE TITLE
Data is only localized for `de` and `fr`

### ISSUE THREAD

**Issue by 974758241** [SAP-samples/cloud-cap-samples#416]
当我设置 accept-language:zh 时候,并没有实现本地化操作!en,de,fr 都是正确的
![image](https://user-images.githubusercontent.com/24804009/197460737-a322e493-93f2-4a14-84aa-f65e768042f4.png)
![image](https://user-images.githubusercontent.com/24804009/197460804-acfe371c-c816-452d-9bae-1ff985263367.png)
所以我要怎么设置才能正确的显示本地化!

**Comment by chgeo** [comment]
English please

**Comment by 974758241** [comment]
When I set accept-language:zh, I didn't localize! en,de,fr are all correct!
So how do I set up the correct display localization!

**Comment by chgeo** [comment]
Assuming this is resolved.
