### ISSUE TITLE
Documentation "Hello World" - file name confusion

### ISSUE THREAD

**Issue by muzijunyan** [SAP-samples/cloud-cap-samples#51]
https://cap.cloud.sap/docs/get-started/hello-world

In the section "Define a service", it's called the file "**say**.cds";
In the section "Run it", however it runs "cds serve **world**.cds". 

It's confusion with the different file names. Based on the sample in the github: https://github.com/SAP-samples/cloud-cap-samples/tree/master/hello, the preferred file name should be aligned to "**world**.cds".

**Comment by David-Kunz** [comment]
Dear Qun,

Thanks for pointing that out, I'll fix this in the newer version of capire.

Best regards,
David
