### ISSUE TITLE
Author name instead of the ID?

### ISSUE THREAD

**Issue by sbarzaghialteaup** [SAP-samples/cloud-cap-samples#59]
Hi,

In the manage books app is possible to show the name of the Author instead of the id?
![image](https://user-images.githubusercontent.com/51169423/80363814-10aca800-8885-11ea-9f64-5f82c593a72b.png)

Thank you

Regards,
Sam

**Comment by chgeo** [comment]
Thanks for catching this.

I have fixed this in #60 with some `UI.TextArrangement` magic of Fiori.  Not an expert there, but with the help of [CAP docs](https://github.wdf.sap.corp/pages/cap/cds/odata-annotations#annotating-annotations) (slightly meta, though) and and [old sample](https://github.com/SAP-samples/cloud-sample-spaceflight-java/blob/859202a90c088739154fb7c4ab02c9a4229ae1c3/srv/fiori-annotations.cds#L33) I could figure it out.

**Comment by sbarzaghialteaup** [comment]
WOW! Much better :-)

Thank you
