### ISSUE TITLE
Expand on draft enabled entity

### ISSUE THREAD

**Issue by sbarzaghialteaup** [SAP-samples/cloud-cap-samples#63]
Hi,

I have a problem using TextArrangement if the associated entity is draft enabled.

Scenario:
```
@odata.draft.enabled
@cds.odata.valuelist
entity Servers
  name : String

@odata.draft.enabled
entity Systems
  name : String
  @Common      : {
                Text            : server.name,
                TextArrangement : #TextOnly
        }
  server : Association to Servers;
```

I edit the "Systems" entity with Fiori then I use the value help on the "server" field, when I close the value help I get the ID instead of the name:
![image](https://user-images.githubusercontent.com/51169423/80763392-b474ad00-8b3e-11ea-893f-cc3b8d392d29.png)

Investigating I found that the get on the "Systems" draft entity returns null in the expand:
```
GET {{server}}/services/Systems(ID=9e1dde5c-9ddb-4700-9dc9-a5108d7150d2,IsActiveEntity=false)?
&$select=server
&$expand=server($select=name)

{
  "@odata.context": "$metadata#Systems(server,ID,IsActiveEntity,server(hostname,ID,IsActiveEntity))/$entity",
  "ID": "9e1dde5c-9ddb-4700-9dc9-a5108d7150d2",
  "IsActiveEntity": false,
  "server": null
}
```
If I remove the draft annotation on the "Servers" entity there is no the problem.
If I create a draft version of the "Server" entity I don't have the problem.
Seems that the expand is trying to read the draft version of the "Servers" entity.

This repository shows the problem:
https://github.com/sbarzaghialteaup/cap_test_draft

Thanks and Best Regards

**Comment by chgeo** [comment]
@johannes-vogel can you take this, or someone from your team?

**Comment by johannes-vogel** [comment]
@chgeo @sbarzaghialteaup We'll investigate and let you know.

**Comment by sbarzaghialteaup** [comment]
> @chgeo @sbarzaghialteaup We'll investigate and let you know.

Hi, news?

**Comment by johannes-vogel** [comment]
@sbarzaghialteaup Please bear with us. We are working on it.

**Comment by vkozyura** [comment]
@sbarzaghialteaup: We implemented navigation using association from draft to active entity. Fix to be provided with the next release.

**Comment by Lisi92** [comment]
In some of our valuehelps, we provide not saved data to the user. It worked fine for a while but i think this change, changed this Select too. So we only get the isactiveentity = true data. Exists there a property or an other solution to control it?  Atm we overwrite it in the begin handler, its a fix but not a solution.
