### ISSUE TITLE
Open SAP Building Applications with SAP Cloud Application Programming Model

### ISSUE THREAD

**Issue by mtecik** [SAP-samples/cloud-cap-samples#64]
hi, during week 2 unit 2 and 3 is not created in my application cloud platform in unit 2 product directory and in unit 3 test directory. Why ?

installation has run and finished. for unit 2
installation completed but not finished. Un
git clone https://github.com/sap-samples/cloud-cap-samples projects/cloud-cap-samples -b openSAP-week2-unit3
cd projects/cloud-cap-samples

user: projects $ git clone https://github.com/sap-samples/cloud-cap-samples projects/cloud-cap-samples -b openSAP-week2-unit3
fatal: destination path 'projects/cloud-cap-samples' already exists and is not an empty directory.
user: projects $ cd projects/cloud-cap-samples
user: cloud-cap-samples $ npm install
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @sap/capire-samples@ install /home/user/projects/projects/cloud-cap-samples
> (npm -s run lerna) && lerna bootstrap --hoist

not found: lerna
+ lerna@3.20.2
added 614 packages from 288 contributors and audited 518 packages in 23.047s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

lerna notice cli v3.20.2
lerna info Bootstrapping 1 package
lerna info Installing external dependencies
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna success Bootstrapped 1 package
removed 614 packages and audited 518 packages in 27.529s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

user: cloud-cap-samples $ cd packages/bookshop
user: bookshop $ cds watch
 
[cds] - running nodemon... 
--ext cds,csn,csv,ts,mjs,cjs,js,json,properties,edmx,xml 
--exec cds serve all --with-mocks --in-memory? 

[cds] - using bindings from: { registry: '/home/user/.cds-services.json' }
[cds] - model loaded from 4 file(s):

  db/schema.cds
  srv/admin-service.cds
  srv/cat-service.cds
  ../../node_modules/@sap/cds/common.cds

[cds] - connect to db { database: ':memory:' }
 > filling sap.capire.bookshop.Authors from db/data/sap.capire.bookshop-Authors.csv
 > filling sap.capire.bookshop.Books from db/data/sap.capire.bookshop-Books.csv
/> successfully deployed to sqlite in-memory db

[cds] - serving AdminService { at: '/admin' }
[cds] - serving CatalogService { at: '/browse', impl: 'srv/cat-service.js' }

[cds] - launched in: 1199.000ms
[cds] - server listening on { url: 'http://localhost:4004' }
[ terminate with ^C ]

GET /browse/Books
GET /browse/Currencies
GET /browse/Orders
[2020-04-30T23:45:40.554Z | WARNING | 1054450]: Method Not Allowed

The Cours Teacher have another Folders. They want now TESTS/Orders.http

best regards

**Comment by chgeo** [comment]
> hi, during week 2 unit 2 and 3 is not created in my application cloud platform in unit 2 product directory and in unit 3 test directory. Why ?
> installation has run and finished. for unit 2
> installation completed but not finished. Un

Trying to guess what you mean here.  Different units of the course need different sample code, e.g. some need the 'Products' folder, some not.  The way this is accomplished is through Git branches.  For most units there is a dedicated branch that you would need to checkout in order to get the correct content.  See the video descriptions where the link to the correct branch for each unit is mentioned.
With this information you can then either:
- Clone the repo anew like with your clone command above.  The second time you do this, you would need to remove the repo first, e.g. with `rm -rf projects/cloud-cap-samples `.  If you try to clone the repo to an existing folder, the clone command fails like above.
- Or in an already cloned repo, switch the branch to the given one, 
   e.g. `git checkout openSAP-week2-unit4` to switch to unit 4.

**Comment by mtecik** [comment]
Hi,

vielen für das Antworten und auch dank für die Zusammenstellung des Kurses.
ich habe bisher nirgends wo gelesen das ich jedes Mal das geklonte löschen soll? 

Die Beispiele habe ich bereits mitgeteilt als JPG.

 

Hier noch ein Beispiel. Week 2 Unit 4

 

Bei mir wird dies angezeigt.



 

 

Aus video

 



 

 

Wie soll ich weitermachen, wenn ich etwas anderes angezeigt bekomme. Ich tippe es auch gerne ab, jedoch fehlt die Hälfte von der Codierung.

 

Oder, CF Login

 

Cloud Foundry Login

This is required later in the demo. In Studio's terminal, execute:

cf login

As input, provide

*	The Cloud Foundry API endpoint, which is usally https://api.cf.eu10.hana.ondemand.com. It can be obtained from the Overview page of your Subaccount in Cloud Cockpit.
*	Your user's email address and password
*	The name of your trial organization and space

 

Was wird hier erklärt?

 

Ich habe mich über Services eingeloggt, weis aber nicht ob dies so richtig ist.



 

Die Übersetzung in den Transkripts sind einfach übersetzt und haben gültigen Satzaufbau. Nicht jeder ist dem Englisch 100% mächtig.

 

 

Was mich aber wundert, dies passiert auch in den Unit Test, das was man ankreuzt wird übersprungen. 

 

Bei der Frage 8



Ich bin mir sicher, hier habe ich cds.serve angelickt. Da bin ich mir 100% sicher, was auch falsch ist. Warum aber hier cds.load angezeigt wird verstehe ich nicht.

 

 

Sorry, das ich dies alles geschrieben habe. Habe den Week 2 mit 40% geschaft, davor Week 1 mit 80%, das beunruhigt mich.

 

Weiter mit WEEK 3

 

 

 

Herzliche Grüße
Mustafa Tecik
Poststr.49
71384 Weinstadt

Tel.  : 07151 6041866
Mobil : 0171 8364466

 

 

 

Von: Christian Georgi 
Gesendet: Dienstag, 5. Mai 2020 12:56
An: SAP-samples/cloud-cap-samples <cloud-cap-samples@noreply.github.com>
Cc: mtecik <mustafa@tecik.com>; Author <author@noreply.github.com>
Betreff: Re: [SAP-samples/cloud-cap-samples] Open SAP Building Applications with SAP Cloud Application Programming Model (#64)

 

hi, during week 2 unit 2 and 3 is not created in my application cloud platform in unit 2 product directory and in unit 3 test directory. Why ?
installation has run and finished. for unit 2
installation completed but not finished. Un

Trying to guess what you mean here. Different units of the course need different sample code, e.g. some need the 'Products' folder, some not. The way this is accomplished is through Git branches. For most units there is a dedicated branch that you would need to checkout in order to get the correct content. See the video descriptions where the link to the correct branch for each unit is mentioned.
With this information you can then either:

*	Clone the repo anew like with your clone command above. The second time you do this, you would need to remove the repo first, e.g. with rm -rf projects/cloud-cap-samples . If you try to clone the repo to an existing folder, the clone command fails like above.
*	Or in an already cloned repo, switch the branch to the given one,
e.g. git checkout openSAP-week2-unit4 to switch to unit 4.

**Comment by mtecik** [comment]
Hallo,

 

Trotz so erstellt wie beschrieben, bekomme ich diesen Fehler

 



 

Bei der Konfiguration kam es nicht zu einem Fehler.

Können Sie mir weiter helfen ?

 

 

Herzliche Grüße
Mustafa Tecik
Poststr.49
71384 Weinstadt

Tel.  : 07151 6041866
Mobil : 0171 8364466

 

 

 

Von: Christian Georgi 
Gesendet: Dienstag, 5. Mai 2020 12:56
An: SAP-samples/cloud-cap-samples <cloud-cap-samples@noreply.github.com>
Cc: mtecik <mustafa@tecik.com>; Author <author@noreply.github.com>
Betreff: Re: [SAP-samples/cloud-cap-samples] Open SAP Building Applications with SAP Cloud Application Programming Model (#64)

 

hi, during week 2 unit 2 and 3 is not created in my application cloud platform in unit 2 product directory and in unit 3 test directory. Why ?
installation has run and finished. for unit 2
installation completed but not finished. Un

Trying to guess what you mean here. Different units of the course need different sample code, e.g. some need the 'Products' folder, some not. The way this is accomplished is through Git branches. For most units there is a dedicated branch that you would need to checkout in order to get the correct content. See the video descriptions where the link to the correct branch for each unit is mentioned.
With this information you can then either:

*	Clone the repo anew like with your clone command above. The second time you do this, you would need to remove the repo first, e.g. with rm -rf projects/cloud-cap-samples . If you try to clone the repo to an existing folder, the clone command fails like above.
*	Or in an already cloned repo, switch the branch to the given one,
e.g. git checkout openSAP-week2-unit4 to switch to unit 4.
