### ISSUE TITLE
this course is for those who are already involved with java and cloud

### ISSUE THREAD

**Issue by mtecik** [SAP-samples/cloud-cap-samples#68]
it is not to understand what is meant here. this time the course is absolutely not for rent but for people who have done this course x times. with this installation i do not understand how to use CF LOGIN. why is this not explained to BSP? i will continue without demos. You probably think we are magicians and understand your thoughts from a distance. watch the video yourself. see how fast the demonstration is and you can hardly watch it. Hey, we took this course because we are renting. and read your pdf translation, this is simply translated via google.

**Comment by danjoa** [comment]
Dito
