### ISSUE TITLE
Says SQLite needs to be installed & Prompts to install it every time!

### ISSUE THREAD

**Issue by bask-alur-gh** [SAP-samples/cloud-cap-samples#72]
Get a prompt to install SQLite in every session of mine!  (This is happening since Week2 tutorials). Here are the Steps: 
1) Clicked SQLTools icon on the IDE, it shows "No Connections.  Click here to add one" (but we did have a datasource configured and used it before!)
2) Checked File>Preferences>Sqltools...shows the connection settings previously entered.
3) Clicked 'Connect' on the status bar of the IDE and it displays "you need to install "sqlite3@4.1.1" to connect to sqlite - bookshop." (which I had installed thrice/four times previously! 
4) Clicked 'Install' to install it successfully again. Now SQLTools > Connections shows the connection to bookshop and the 'Connect' icon next to it and clicking on it shows the views and tables as before.
5) Signout/close the session and come back into AppStudio later (after restart) and step1 occurs again.

Kindly help.  Is this a bug, or do I need to be following a specific sequence of steps?  Thanks in advance!

**Comment by ShimonBenYair** [comment]
This issue need to be solved when this PR: https://github.com/mtxr/vscode-sqltools/pull/554
will be merged

**Comment by bask-alur-gh** [comment]
Amazing super fast attempt to resolve this issue and reply, so thanks a lot first!  The issue persists at this time, I tried it just now and still asks to install SQLite and after installing it works fine (same as steps 1-5 above).  I'll retry after 1 day.  Thanks again.

**Comment by chgeo** [comment]
Closing this one, assuming issue is solved.
