### ISSUE TITLE
wee3 unit 4 

### ISSUE THREAD

**Issue by mtecik** [SAP-samples/cloud-cap-samples#76]
hi, 
on Building Applications with SAP Cloud Application Programming ModelChristian Georgi
Week 3 unit 4 -  I have found the problem service offering 'hana' not
after the input - cf create-service hana hdi-shared bookshop-db-hdi-container -
there was no error before that.

best regards
![Bild1](https://user-images.githubusercontent.com/64591225/81436525-ef439a00-9169-11ea-8940-a0e7409c65d0.jpg)

**Comment by charbelkisso** [comment]
if you are running on trial account you should use another service offering called hanatrial instead of hana

**Comment by chgeo** [comment]
Right, on the trial account service creation needs to happen with 
`cf create-service hanatrial hdi-shared bookshop-db-hdi-container`
