### ISSUE TITLE
week4 Unit 4 

### ISSUE THREAD

**Issue by mtecik** [SAP-samples/cloud-cap-samples#83]
week4 Unit 4
in the demo the page of the instructor in the attachment, 
![WEEK4-U4-1](https://user-images.githubusercontent.com/64591225/81997815-2249ca00-9651-11ea-979d-b0933d5fe163.JPG)
![WEEK4-U4-myLocal](https://user-images.githubusercontent.com/64591225/81997819-237af700-9651-11ea-9092-e441899382da.JPG)

week4 Unit 4
in the demo the page of the docent in the facility WEEK4-U4-1, and my view when Week4 U4 is selected 
WEEK4-U4-myLocal. it is not the same directory structure.
what is the next step?

**Comment by chgeo** [comment]
Sorry, but I don't get what your are saying.
Yes, the files in the various branches of the repository are different.  This might explain the differences that you see.
