### ISSUE TITLE
Why I got 403 error: 'CREATE is only allowed with static instance-based authorization'

### ISSUE THREAD

**Issue by fourmatrix** [SAP-samples/cloud-cap-samples#84]
Hello,

I add authentication to my FooService and Books:

annotate FooService with @(requires: 'authenticated-user');
annotate FooService.Books with @(restrict: [
  {
    grant: ['READ', 'CREATE', 'WRITE', 'DELETE'],
    where: 'id = $user.id'
  }
]);

When create a Books, I got 403 error with message : 'CREATE is only allowed with static instance-based authorization' , how can I fix it?

**Comment by pianocktail** [comment]
You cannot use CREATE and WRITE as it comprises 'INSERT' and on 'INSERT'  you cannot use where clauses.
You need your authorization only for READ , UPDATE , DELETE.
On the intial creation of the data record the 'id' should be set to the '$user.id' automatically

**Comment by fourmatrix** [comment]
@pianocktail  I got it, thank you very much!
