### ISSUE TITLE
error when deploying following openSAP-week3-unit5

### ISSUE THREAD

**Issue by silasd23** [SAP-samples/cloud-cap-samples#85]
Hello everyone ! 

I'm having some troble whyle trying to run the example of week 3 unit 5 of open sap course 
https://github.com/SAP-samples/cloud-cap-samples/tree/openSAP-week3-unit5
https://open.sap.com/courses/cp7/items/y6qAYiWpxGJqIpCYpwzn6

in the homepage i have this errors :
![image](https://user-images.githubusercontent.com/49450546/82241840-bb6c2f80-9934-11ea-8ae0-7ffdae3b002d.png)

in the Books page i have this errors : 
![image](https://user-images.githubusercontent.com/49450546/82241892-d5a60d80-9934-11ea-801b-f5f360737830.png)

i followed the steps in the demo presentend in the course and also checked in the git repository, can someone help me to understand what i have made wrong?

**Comment by chgeo** [comment]
I think must of the errors is client-side stuff from UI5, which may be ignored.  For example, the `ServerInfos` requests are optional.
What is the actual perceived error that you get?  Which UIs do not work?

Also CCing @pianocktail, who is the expert for the unit.

**Comment by pianocktail** [comment]
The only reason for having the "app" in the CF deployment in the example is to show how the approuter is doing the redirection to XSUAA and getting a JWT token.  Testing the authorizations is much easier to be done locally. This is also what is shown in the demos.

**Comment by silasd23** [comment]
> shown

Yes I know but my problem is that after following all the steps to deploy to Cloud and I execute the command bellow I get errors in the files generated:
![image](https://user-images.githubusercontent.com/49450546/82434500-d5b82180-9a8a-11ea-9898-7a29543f24f4.png)

Follow evidence: 
![image](https://user-images.githubusercontent.com/49450546/82434857-6262df80-9a8b-11ea-93b9-4b991794a2da.png)

If I deploy this as it is the deployment process will be done with success but if I go to the App i do not have any data in the Database. If I do some changes and fix the files and then do the deploy i got the same error.

Can you or somewone tell me what is wrong ?

**Comment by chgeo** [comment]
The error above in the editor can be ignored.  That's a glitch in the editor.

For the missing data, how have you verified this?  Troubleshooting tips:
- Check in the HANA tables.
- If this is fine, check the pure odata request like `/catalog/Books`.
- If this is working, only check from the UI.  Do you see columns in the table?  If not, this indicates no `UI.LineItems` annotations being present.

**Comment by chgeo** [comment]
This issue channel will be closed.  If the error persists, please report it in our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).
