### ISSUE TITLE
Doc Feedback: Can't navigate back from search results

### ISSUE THREAD

**Issue by boghyon** [SAP-samples/cloud-cap-samples#86]
1. Open https://cap.cloud.sap/
2. Click on the search button (top right) and enter something
3. Try to navigate back

**Comment by renejeglinsky** [comment]
Good morning,

did you try clicking the search button again? It closes the search and your are back where you've been before.

Regards,
René

**Comment by boghyon** [comment]
Thanks! Clicking on the button again works. Since the search results covered the whole page, it looked like I was being navigated to another page, just without changing the browser history / URL.

**Comment by boghyon** [comment]
@renejeglinsky I still believe that the search result should get its own history entry. After clicking on one of the search results, how do you go back to the results?

The main problem is that the result page covers the whole document, imitating a page navigation. But there was no navigation which is quite confusing.

It would be nice if this issue could be addressed internally.

**Comment by renejeglinsky** [comment]
We'll evaluate it. You'll see it in our release notes as soon as we've implemented it.

https://cap.cloud.sap/docs/releases/

**Comment by chgeo** [comment]
We are about to provide this.  Should be available w/ the next release soon.

**Comment by iwonahahn** [comment]
@boghyon We have good news for you. The search is now stored in browser history. This way, you can come back to the search list after you have navigated to the results. Also, you can now bookmark and share your search. Just copy the .../search?q=... URL from your browser address bar. I hope this helps and the issue is resolved?

**Comment by boghyon** [comment]
Awesome! Yes, I just tested it. Works great! Thank you so much for responding quickly and enhancing the doc. 👍
