### ISSUE TITLE
Handler for GET request

### ISSUE THREAD

**Issue by robertopini** [SAP-samples/cloud-cap-samples#87]
Let's suppose i want to create a static helloworld service, which should simply return a string when called. Am i forced to define a function ?

Another way to see the problem:
```
service helloworld {
// empty service with no functions/entities exposed 
}
```

How do i register an handler (let's suppose i'm using node)  in this case for the "GET /helloworld" request ? Is it possibile ?

**Comment by chgeo** [comment]
@David-Kunz do you see a way to achieve this?
Alternatively, one might go with `/hello/world`.

**Comment by David-Kunz** [comment]
Hi @robertopini ,

Yes, you're forced to write a function.

We only support handlers for actions, functions and entities. Not for services themselves.

Best regards,
David
