### ISSUE TITLE
Tree Table, oData v2

### ISSUE THREAD

**Issue by chrishanusch** [SAP-samples/cloud-cap-samples#88]
Hello,
we want to create a TreeTable using oData v2. Our CDS entities look like this:

agreements > licenses > positions.

The agreements are loaded on a detail page while licenses and positions should be loaded within a TreeTable as parent and children nodes ( https://openui5.hana.ondemand.com/entity/sap.ui.table.TreeTable/sample/sap.ui.table.sample.TreeTable.BasicODataTreeBinding/code/localService%2Fmockdata%2FNodes.json ).
How has the service to look like in order to achieve this?

**Comment by chgeo** [comment]
May you ask this again over on our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce)?  There is a higher chance there that you will get answers or hints.
Thanks.
