### ISSUE TITLE
Not able to create using Fiori draft.

### ISSUE THREAD

**Issue by Nandanchaturvedi** [SAP-samples/cloud-cap-samples#92]
I have created a project with Fiori draft enabling but getting the following error while clicking create on the Fiori tile.

> NEW PfgRequests null
>>> POST DSPPfgService.PfgRequests_drafts
[2020-06-03T14:50:43.070Z | ERROR | 1894620]: Cannot convert undefined or null to object
[INTERNAL ERROR] TypeError: Cannot convert undefined or null to object
    at removeDraftUUID (C:\Users\i077624\OneDrive - SAP SE\DSP\CAP Learning\DSPPortal\node_modules\@sap\cds-runtime\lib\cds-services\services\utils\draftUtils.js:224:5)
    at C:\Users\i077624\OneDrive - SAP SE\DSP\CAP Learning\DSPPortal\node_modules\@sap\cds-runtime\lib\cds-services\services\handlers\onCreateDraft.js:96:14
Please report this error.

**Comment by chgeo** [comment]
@David-Kunz @johannes-vogel can you help here?

**Comment by David-Kunz** [comment]
Hi @Nandanchaturvedi ,

Can you give us more insights?

- Link to your repository
- Which cds version


Thanks and best regards,
David

**Comment by chgeo** [comment]
This issue channel will be closed.  If the error persists, please report it in our [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).
