### ISSUE TITLE
fiori sample (sap.fe) is no more working with sapui5 1.78

### ISSUE THREAD

**Issue by hschaefer123** [SAP-samples/cloud-cap-samples#95]
With the latest sapui5, the fiori sample is no more working!

As a workaround, add sap.fe.templates to required libs
```
data-sap-ui-libs="sap.m, sap.ushell, sap.collaboration, sap.ui.layout, sap.fe.templates"
```
Also in each app component manifest replace dependecy sa.fe to
```
"dependencies": {
            "libs": {
                "sap.fe.templates": {}
            }
        }
```
because with 1.78 a deprecated dialog will be shown for sap.fe.
sap.fe.template internally requires sap.fe.core and sap.fe.macros so this seems to be the new core ref.

Maybe you can create a ticket for the sapui5 team, because the sandbox ushell error seems to be comming from async loading manifest dependencies.

Regards Holger

**Comment by chgeo** [comment]
This seems to be handled in PR #98
