### ISSUE TITLE
Need an example on how to add a 'Fiori Launchpad Site' module

### ISSUE THREAD

**Issue by krisho007** [SAP-samples/cloud-cap-samples#99]
If I need to add my CAP app with a Fiori UI to an SCP FLP, CAP app needs a 'Fiori Launchpad Site' module. This does not seem to be straight forward.
An example on how to do this would be great.

**Comment by chgeo** [comment]
Thanks.
Please post this question over in the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) where there is a higher chance that someone can answer it.
